"""
Builds a downloadable Word document summarising the analysis.
"""

from docx import Document
from io import BytesIO


def build_docx(scenario_text: str, contract_formed: bool, element_results: dict, elements_by_id: dict) -> bytes:
    doc = Document()
    doc.add_heading("Contract Formation Analysis", 0)

    doc.add_heading("Contract / Scenario Text", level=1)
    # Keep the document readable — truncate very long contracts in the export.
    doc.add_paragraph(scenario_text[:3000] + ("..." if len(scenario_text) > 3000 else ""))

    doc.add_heading("Overall Conclusion", level=1)
    verdict_text = "A contract was likely formed." if contract_formed else "A contract was likely NOT formed."
    doc.add_paragraph(verdict_text)

    doc.add_heading("Formation Elements", level=1)
    for element_id, result in element_results.items():
        element = elements_by_id[element_id]
        if element["category"] != "formation":
            continue
        doc.add_heading(element["name"], level=2)
        doc.add_paragraph(f"Met: {'Yes' if result['met'] else 'No'}")
        doc.add_paragraph(result["reason"])

    doc.add_heading("Validity Considerations", level=1)
    for element_id, result in element_results.items():
        element = elements_by_id[element_id]
        if element["category"] != "validity":
            continue
        doc.add_heading(element["name"], level=2)
        doc.add_paragraph(f"Met: {'Yes' if result['met'] else 'No'}")
        doc.add_paragraph(result["reason"])

    doc.add_paragraph()
    doc.add_paragraph(
        "This analysis was generated by an AI-assisted tool for study purposes "
        "and does not constitute legal advice."
    )

    buffer = BytesIO()
    doc.save(buffer)
    return buffer.getvalue()